apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.serviceType }}
  ports:
    - name: {{ include "chart.service-port-name" . }}
      port: {{ include "chart.service-port" . }}
      targetPort: {{ include "chart.container-port-name" . }}
      nodePort: {{ .Values.nodePort }}
      protocol: TCP
  selector:
  {{- include "chart.labels" . | nindent 4 }}